import { getSaveSummary, loadGameState, resetGameState, saveGameState } from './game-state.js';
import { createGameUI } from './game-ui.js';
import { TOWN_PROJECTS } from './game-catalog.js';
import { registerTravelDistance } from './combat-services.js';
import { CAVE_CELL_SIZE, caveCellToWorld } from './cave-data.js';
import { completeLowerWays, enterLowerWays, getCaveRunView, leaveLowerWays, markCaveBossStarted, resetCaveBossAfterCombat, updateCavePosition, useNearbyCaveHealing } from './cave-services.js';
import { createLowerWaysVisuals, drawCaveMiniMap } from './cave-visuals.js?v=16';
import { dampAngle, routeHeading, routeLookAhead, smoothNavigationPath } from './navigation-utils.js?v=16';
import { recordServiceVisit, recordTownArrival } from './journey-services.js';
import { createAdventureBackdrop, createLivingTowns, createSkyLife, decorateAdventureWorld, drawAdventureMap, drawLiveMiniMap } from './world-visuals.js';
import {
  WORLD_LANDMARKS,
  WORLD_LIMIT,
  WORLD_POSITION_SAVE_INTERVAL,
  WORLD_ROUTES,
  getAreaAtPosition,
  getFastTravelLandmarks,
  getKnownLandmarks,
  isLandmarkKnown,
  isGuardianAvailable,
  readHostedWorldPosition,
  writeHostedWorldPosition
} from './world-data.js';

(()=>{'use strict';
const $=id=>document.getElementById(id),canvas=$('view'),status=$('status'),loader=$('loader'),loadingText=$('loadingText'),bar=$('bar'),errorBox=$('error'),tap=$('tap'),walk=$('walk'),plan=$('plan'),planCanvas=$('planCanvas'),mapDestinations=$('mapDestinations'),miniMapPanel=$('miniMap'),miniMapToggle=$('miniMapToggle'),miniCanvas=$('miniMapCanvas'),miniArea=$('miniArea'),miniSafety=$('miniSafety'),playerVitals=$('playerVitals'),playerHealthText=$('playerHealthText'),playerHealthFill=$('playerHealthFill'),caveHealth=$('caveHealth'),caveHealthFill=$('caveHealthFill'),caveBrief=$('caveBrief'),npcSpeech=$('npcSpeech'),npcName=$('npcName'),npcLine=$('npcLine'),worldServices=$('worldServices'),unlockOverlay=$('unlockOverlay');
function fail(e){const m=(e&&e.stack)||String(e);console.error(e);errorBox.style.display='block';errorBox.textContent='Emberfall error:\n'+m;status.textContent='Error';loader.classList.add('hide')}
addEventListener('error',e=>fail(e.error||e.message));addEventListener('unhandledrejection',e=>fail(e.reason));
const saveBridge=loadGameState();
let gameState=saveBridge.state,saveSummary=getSaveSummary(gameState);
const serviceMeshes=new Map(),serviceButtons=new Map(),serviceDecorationLevels=new Map(),landmarkMeshes=new Map(),landmarkButtons=new Map();let serviceLots=[],landmarkLots=[],pendingService=null,pendingLandmark=null,pendingCaveAction=null;
window.EmberfallState=gameState;
window.EmberfallSave={...saveBridge,summary:saveSummary};
function commitGameState(action){const saved=saveGameState(gameState);gameState=saved.state;saveBridge.state=gameState;saveSummary=getSaveSummary(gameState);window.EmberfallState=gameState;window.EmberfallSave={...saveBridge,state:gameState,summary:saveSummary,lastAction:action,saveErrors:saved.errors};syncTownServices(action);updatePlayerHealth();EmberDebug.log('SAVE',action,saved.written,saveSummary,saved.errors);return saved}
function resetProgress(){const reset=resetGameState();EmberDebug.log('SAVE','progress reset',reset.removed,reset.errors);if(reset.errors.length){gameUI.notify('This browser could not fully clear the save.','bad');return false}gameUI.notify('Progress cleared · restarting Emberfall','gold');setTimeout(()=>location.reload(),520);return true}
function revealBuildingUpgrade(id){const service=serviceLots.find(entry=>entry.id===id),building=serviceMeshes.get(id);if(!service||!building)return false;setServiceTarget(service);gameUI.notify(`Walking over to see ${service.name} change…`,'gold');return true}
EmberDebug.log('SAVE',saveBridge.found?'compatible save loaded':'no compatible save found; using fresh state',saveBridge.sourceKey||'fresh',saveSummary);
const gameUI=createGameUI({getState:()=>gameState,commit:commitGameState,onJourneyAction:journeyWorldAction,onBuildingUpgrade:revealBuildingUpgrade,onVisualStyle:value=>{applyStyle(value);if(caveMode())applyCaveAtmosphere()},getVisualStyle:()=>style,onReset:resetProgress});
window.EmberfallUI=gameUI;
const MOBILE_PROFILE=matchMedia('(pointer:coarse)').matches||innerWidth<720,renderer=new THREE.WebGLRenderer({canvas,antialias:!MOBILE_PROFILE||devicePixelRatio<1.8,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,MOBILE_PROFILE?1.25:1.65));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(62,1,.08,900),ray=new THREE.Raycaster(),mouse=new THREE.Vector2();scene.fog=new THREE.Fog(0xb8c7c3,110,520);
let hemi,sun,fill,terrain,grassShader,targetRing,townLife,skyLife,caveWorld,roads=[],roadSamples=[],lots=[],flatten=[],colliders=[],assets={},nav=[],navI=0,last=performance.now(),lastMiniMap=0,lastNpcSpeech=0,yaw=0,pitch=-.04,routeHeadingReturn=0,style='realistic',distanceSinceSave=0,positionDirty=false,wasCombatActive=Boolean(gameState.explore?.combat);
const initialCaveView=getCaveRunView(gameState),initialCaveCell=caveCellToWorld(initialCaveView.layout,initialCaveView.run.cell),savedPosition=readHostedWorldPosition(gameState.explore),initialCavePosition=initialCaveView.run.active?(initialCaveView.run.position||[initialCaveCell.x,initialCaveCell.z]):null,player={x:initialCavePosition?.[0]??savedPosition.x,z:initialCavePosition?.[1]??savedPosition.z,y:2},SEED=48731,WORLD=350;
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function lerp(a,b,t){return a+(b-a)*t}function smooth(a,b,x){x=clamp((x-a)/(b-a),0,1);return x*x*(3-2*x)}
function rngMaker(seed){return()=>{let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}let rnd0=rngMaker(SEED);const rnd=(a,b)=>a+rnd0()*(b-a),pick=a=>a[(rnd0()*a.length)|0];
function baseH(x,z){let h=Math.sin(x*.018)*1.9+Math.cos(z*.016)*1.4+Math.sin((x+z)*.028)*.7;h+=26*Math.exp(-((x+235)**2+(z+255)**2)/4300)+34*Math.exp(-((x-10)**2+(z+300)**2)/5200)+28*Math.exp(-((x-240)**2+(z+235)**2)/4500)+15*Math.exp(-((x+300)**2+(z-20)**2)/5000)+13*Math.exp(-((x-300)**2+(z+10)**2)/5200);const valley=Math.exp(-(x*x/13000+(z-4)*(z-4)/21000));return h*(1-.42*valley)}
function height(x,z){let h=baseH(x,z);for(const f of flatten){const c=Math.cos(-f.r),s=Math.sin(-f.r),dx=x-f.x,dz=z-f.z,lx=dx*c-dz*s,lz=dx*s+dz*c,out=Math.max(Math.abs(lx)-f.w/2,Math.abs(lz)-f.d/2);if(out<f.m)h=lerp(h,f.y,1-smooth(0,f.m,Math.max(0,out)))}return h}
function lighting(){hemi=new THREE.HemisphereLight(0xdcebf4,0x635c4e,.9);scene.add(hemi);sun=new THREE.DirectionalLight(0xffd09a,2.25);sun.position.set(-120,160,95);sun.castShadow=true;sun.shadow.mapSize.set(MOBILE_PROFILE?1024:2048,MOBILE_PROFILE?1024:2048);sun.shadow.camera.left=-110;sun.shadow.camera.right=110;sun.shadow.camera.top=110;sun.shadow.camera.bottom=-110;sun.shadow.camera.near=10;sun.shadow.camera.far=430;sun.shadow.bias=-.0004;scene.add(sun,sun.target);fill=new THREE.DirectionalLight(0x8cb0d4,.3);fill.position.set(110,60,-100);scene.add(fill)}
function sky(){const m=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{top:{value:new THREE.Color(0x668fac)},mid:{value:new THREE.Color(0xbec8bd)},bot:{value:new THREE.Color(0xe9bd87)}},vertexShader:'varying vec3 p;void main(){p=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform vec3 top,mid,bot;varying vec3 p;void main(){float h=normalize(p).y*.5+.5;vec3 c=h>.5?mix(mid,top,(h-.5)*2.):mix(bot,mid,h*2.);gl_FragColor=vec4(c,1.);}'});scene.userData.sky=m;scene.add(new THREE.Mesh(new THREE.SphereGeometry(650,28,14),m))}
function applyStyle(s){style=s;document.querySelectorAll('[data-style]').forEach(b=>b.classList.toggle('active',b.dataset.style===s));if(s==='realistic'){renderer.toneMappingExposure=1.08;scene.fog.color.setHex(0xb8c7c3);scene.fog.near=110;scene.fog.far=520;sun.intensity=2.25;fill.intensity=.3;hemi.intensity=.9;scene.userData.sky.uniforms.top.value.setHex(0x668fac);scene.userData.sky.uniforms.mid.value.setHex(0xbec8bd);scene.userData.sky.uniforms.bot.value.setHex(0xe9bd87)}else{renderer.toneMappingExposure=.94;scene.fog.color.setHex(0x87949d);scene.fog.near=82;scene.fog.far=360;sun.intensity=3.05;fill.intensity=.07;hemi.intensity=.58;scene.userData.sky.uniforms.top.value.setHex(0x44566b);scene.userData.sky.uniforms.mid.value.setHex(0x8e918f);scene.userData.sky.uniforms.bot.value.setHex(0xcc8955)}}document.querySelectorAll('[data-style]').forEach(b=>b.onclick=()=>{applyStyle(b.dataset.style);if(caveMode())applyCaveAtmosphere()});
function caveMode(){return Boolean(caveWorld&&gameState.explore?.caveRun?.active&&gameState.explore?.area==='cave')}
function groundHeight(x,z){return caveMode()?caveWorld.floorY:height(x,z)}
function currentAreaInfo(){return caveMode()?{area:'cave',townId:null,landmark:WORLD_LANDMARKS.find(entry=>entry.id==='cave')}:getAreaAtPosition(player)}
function applyCaveAtmosphere(){scene.fog.color.setHex(0x111b20);scene.fog.near=7;scene.fog.far=MOBILE_PROFILE?76:92;renderer.toneMappingExposure=1.12;sun.intensity=.14;fill.intensity=.3;hemi.intensity=.28}
function refreshAtmosphere(){applyStyle(style);if(caveMode())applyCaveAtmosphere()}
const CITY='https://cdn.jsdelivr.net/gh/KenneyNL/Starter-Kit-City-Builder@main/models/',PROP='https://cdn.jsdelivr.net/gh/ETdoFresh/kenney.nl@master/fantasy-town-kit-1.0/Models/GLTF%20format/';
const defs=[['a',CITY+'building-small-a.glb',7.2],['b',CITY+'building-small-b.glb',7.5],['c',CITY+'building-small-c.glb',7.8],['d',CITY+'building-small-d.glb',7.6],['garage',CITY+'building-garage.glb',5.8],['tree',PROP+'tree.glb',5],['tree2',PROP+'treeCrooked.glb',5.2],['tree3',PROP+'treeHighRound.glb',6.4],['fountain',PROP+'fountainRoundDetail.glb',2.2],['stallR',PROP+'stallRed.glb',2.5],['stallG',PROP+'stallGreen.glb',2.5],['bench',PROP+'stallBench.glb',1],['cart',PROP+'cartHigh.glb',2],['lamp',PROP+'lantern.glb',1.9],['fence',PROP+'fence.glb',1.25],['rock',PROP+'rockLarge.glb',1.7]];
const servicePlans=[
 {id:'mine',name:'Greyfen Town Mine',tab:'work',k:'garage',x:29,z:32,sc:1.08},
 {id:'smelter',name:TOWN_PROJECTS.smelter.name,tab:'work',k:'garage',x:38,z:3,sc:1.08},
 {id:'forge',name:TOWN_PROJECTS.forge.name,tab:'forge',k:'d',x:-29,z:27,sc:1.08},
 {id:'market',name:`${TOWN_PROJECTS.market.name} Hall`,tab:'market',k:'b',x:13,z:-24,sc:1.04},
 {id:'inn',name:TOWN_PROJECTS.inn.name,tab:'town',k:'c',x:-28,z:-37,sc:1.1}
];
function loadModel([k,url,h]){return new Promise(res=>{let done=false,t=setTimeout(()=>{if(!done){done=true;res(false)}},7000),L=new THREE.GLTFLoader();L.load(url,g=>{if(done)return;done=true;clearTimeout(t);try{let o=g.scene,b=new THREE.Box3().setFromObject(o),sz=new THREE.Vector3();b.getSize(sz);o.scale.setScalar(h/Math.max(.001,sz.y));b.setFromObject(o);o.position.y-=b.min.y;b.setFromObject(o);b.getSize(sz);o.userData.size=sz.clone();o.traverse(q=>{if(q.isMesh){q.castShadow=q.receiveShadow=true;if(q.material)q.material=q.material.clone()}});assets[k]=o;res(true)}catch(e){console.warn(k,e);res(false)}},undefined,()=>{if(!done){done=true;clearTimeout(t);res(false)}})})}
async function loadBuildings(){let b=defs.slice(0,5),n=0;await Promise.all(b.map(async d=>{if(await loadModel(d))n++;bar.style.width=(n/b.length*100)+'%';status.textContent=`Buildings ${n}/5`}));return n}
let adventureDetailBuilt=false;
function loadProps(){Promise.all(defs.slice(5).map(loadModel)).then(()=>{decorateProps();caveWorld?.addRockAsset(assets.rock);if(!adventureDetailBuilt){adventureDetailBuilt=true;decorateAdventureWorld({THREE,scene,assets,height,propPlace,roadDist,landmarks:WORLD_LANDMARKS,lots,addCollider:(x,z,r)=>colliders.push({x,z,r}),mobile:MOBILE_PROFILE});drawPlan();EmberDebug.log('WORLD','regional identities and town detail ready')}status.textContent=caveMode()?'Exploring the Lower Ways':'World ready · regional detail loaded'}).catch(()=>{})}
function key(x,z){return x+','+z}function waterBlock(x,z){return Math.hypot(x-118,z+95)<44}
function heapPush(heap,item){let index=heap.length;heap.push(item);while(index>0){const parent=(index-1)>>1;if(heap[parent].f<=item.f)break;heap[index]=heap[parent];index=parent}heap[index]=item}
function heapPop(heap){const first=heap[0],last=heap.pop();if(heap.length){let index=0;while(true){let child=index*2+1;if(child>=heap.length)break;if(child+1<heap.length&&heap[child+1].f<heap[child].f)child++;if(heap[child].f>=last.f)break;heap[index]=heap[child];index=child}heap[index]=last}return first}
function astar(a,b,step=6){const min=-132,max=132,N=Math.round((max-min)/step)+1,toG=p=>[clamp(Math.round((p[0]-min)/step),0,N-1),clamp(Math.round((p[1]-min)/step),0,N-1)],toW=(x,z)=>[min+x*step,min+z*step],[sx,sz]=toG(a),[ex,ez]=toG(b),open=[{x:sx,z:sz,g:0,f:0}],came=new Map(),gs=new Map([[key(sx,sz),0]]),closed=new Set(),dirs=[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]];let loops=0;while(open.length&&loops++<9000){open.sort((u,v)=>u.f-v.f);let c=open.shift(),ck=key(c.x,c.z);if(closed.has(ck))continue;closed.add(ck);if(c.x===ex&&c.z===ez){let p=[];while(c){p.push(toW(c.x,c.z));c=came.get(key(c.x,c.z))}p.reverse();p[0]=a;p[p.length-1]=b;return chaikin(p)}for(const [dx,dz] of dirs){let nx=c.x+dx,nz=c.z+dz;if(nx<0||nz<0||nx>=N||nz>=N)continue;let w=toW(nx,nz);if(waterBlock(...w))continue;let cw=toW(c.x,c.z),slope=Math.abs(baseH(...w)-baseH(...cw)),ng=c.g+Math.hypot(dx,dz)*(1+slope*2.5),nk=key(nx,nz);if(ng<(gs.get(nk)??1e9)){gs.set(nk,ng);came.set(nk,c);open.push({x:nx,z:nz,g:ng,f:ng+Math.hypot(nx-ex,nz-ez)})}}}return[a,b]}
function chaikin(p){for(let k=0;k<2;k++){let n=[p[0]];for(let i=0;i<p.length-1;i++){let a=p[i],b=p[i+1];n.push([a[0]*.75+b[0]*.25,a[1]*.75+b[1]*.25],[a[0]*.25+b[0]*.75,a[1]*.25+b[1]*.75])}n.push(p[p.length-1]);p=n}return p}
function sample(poly,spacing=2.6){let out=[];for(let i=0;i<poly.length-1;i++){let a=poly[i],b=poly[i+1],d=Math.hypot(b[0]-a[0],b[1]-a[1]),n=Math.max(1,Math.ceil(d/spacing));for(let j=0;j<n;j++){let t=j/n;out.push([lerp(a[0],b[0],t),lerp(a[1],b[1],t)])}}out.push(poly.at(-1));return out}
function addRoad(p,w=5,k='side'){let s=sample(p);roads.push({p,w,k});for(let i=0;i<s.length;i++){let a=s[Math.max(0,i-1)],b=s[Math.min(s.length-1,i+1)],tx=b[0]-a[0],tz=b[1]-a[1],l=Math.hypot(tx,tz)||1;tx/=l;tz/=l;roadSamples.push({x:s[i][0],z:s[i][1],tx,tz,nx:-tz,nz:tx,w,k})}}
function roadsGenerate(){roads=[];roadSamples=[];let A={south:[0,96],market:[0,8],north:[10,-101],west:[-62,34],east:[62,30],hall:[-48,-57]};addRoad(astar(A.south,A.market),7,'main');addRoad(astar(A.market,A.north),6.5,'main');addRoad(astar(A.market,A.west),5.1);addRoad(astar(A.market,A.east),5.1);addRoad(astar(A.market,A.hall),4.8);addRoad(astar(A.west,[-30,-42]),4);addRoad(astar(A.east,[42,-45]),4);for(let i=0;i<5;i++){let s=pick(roadSamples.filter((_,j)=>j%15===0&&Math.abs(_.z)<82)),ang=rnd(0,Math.PI*2),len=rnd(20,35),e=[clamp(s.x+Math.cos(ang)*len,-86,86),clamp(s.z+Math.sin(ang)*len,-84,88)];if(!waterBlock(...e))addRoad(astar([s.x,s.z],e),3.4,'lane')}for(const route of WORLD_ROUTES)addRoad(chaikin(route.points.map(point=>[...point])),route.width,'world')}
function segD(px,pz,a,b){let vx=b[0]-a[0],vz=b[1]-a[1],wx=px-a[0],wz=pz-a[1],t=clamp((vx*wx+vz*wz)/(vx*vx+vz*vz||1),0,1);return Math.hypot(px-a[0]-vx*t,pz-a[1]-vz*t)}
function roadDist(x,z){let d=1e9;for(const r of roads)for(let i=0;i<r.p.length-1;i++)d=Math.min(d,segD(x,z,r.p[i],r.p[i+1])-r.w/2);return d}
function slopeFoot(x,z,w,d,r){let c=Math.cos(r),s=Math.sin(r),hs=[];for(const [lx,lz] of [[-w/2,-d/2],[w/2,-d/2],[-w/2,d/2],[w/2,d/2],[0,0]])hs.push(baseH(x+lx*c+lz*s,z-lx*s+lz*c));return{lo:Math.min(...hs),hi:Math.max(...hs),avg:hs.reduce((a,b)=>a+b)/hs.length}}
function lotsGenerate(){
 lots=[];serviceLots=[];landmarkLots=[];flatten=[];colliders=[];
 flatten.push({x:0,z:8,r:0,w:28,d:28,y:baseH(0,8),m:5});
 for(const plan of servicePlans){
  const src=assets[plan.k];if(!src)continue;
  const sz=src.userData.size,w=sz.x*plan.sc,d=sz.z*plan.sc,rot=Math.atan2(-plan.x,8-plan.z),sl=slopeFoot(plan.x,plan.z,w,d,rot),rad=Math.hypot(w,d)*.45;
  const lot={...plan,rot,w,d,rad,modelH:sz.y*plan.sc,service:true};lots.push(lot);serviceLots.push(lot);
  flatten.push({x:plan.x,z:plan.z,r:rot,w:w+1.5,d:d+1.5,y:sl.avg,m:3.5});colliders.push({x:plan.x,z:plan.z,r:rad*.72});
 }
 for(const landmark of WORLD_LANDMARKS){
  if(landmark.id==='town')continue;
  const src=assets[landmark.building];if(!src)continue;
  const sc=landmark.kind==='town'?1.24:1.12,sz=src.userData.size,w=sz.x*sc,d=sz.z*sc,rot=Math.atan2(landmark.entry.x-landmark.x,landmark.entry.z-landmark.z),sl=slopeFoot(landmark.x,landmark.z,w,d,rot),rad=Math.hypot(w,d)*.45;
  const lot={k:landmark.building,x:landmark.x,z:landmark.z,rot,sc,w,d,rad,modelH:sz.y*sc,landmark:true,landmarkId:landmark.id};lots.push(lot);landmarkLots.push(lot);
  flatten.push({x:lot.x,z:lot.z,r:rot,w:w+2,d:d+2,y:sl.avg,m:5});colliders.push({x:lot.x,z:lot.z,r:rad*.72});
  if(landmark.kind==='town')for(const [index,offset] of [[0,[-14,9]],[1,[14,10]]]){const key=['b','c'][index],side=assets[key];if(!side)continue;const sideSc=1.02,sideSize=side.userData.size,sideW=sideSize.x*sideSc,sideD=sideSize.z*sideSc,x=landmark.x+offset[0],z=landmark.z+offset[1],sideRot=rot+(index?-.24:.24),sideSlope=slopeFoot(x,z,sideW,sideD,sideRot),sideRad=Math.hypot(sideW,sideD)*.45;lots.push({k:key,x,z,rot:sideRot,sc:sideSc,w:sideW,d:sideD,rad:sideRad,landmarkCluster:landmark.id});flatten.push({x,z,r:sideRot,w:sideW+1.5,d:sideD+1.5,y:sideSlope.avg,m:4});colliders.push({x,z,r:sideRad*.72})}
 }
 const keys=['a','b','c','d','garage'];
 for(const R of roads){if(R.k==='world')continue;let S=sample(R.p,R.k==='main'?13:15);for(let i=2;i<S.length-2;i+=2){let p=S[i],p0=S[i-1],p1=S[i+1],tx=p1[0]-p0[0],tz=p1[1]-p0[1],tl=Math.hypot(tx,tz)||1;tx/=tl;tz/=tl;let nx=-tz,nz=tx;for(const side of [-1,1]){if(rnd0()<.24||lots.length>=48)continue;let k=pick(keys),src=assets[k];if(!src)continue;let sc=k==='garage'?rnd(.9,1.05):rnd(.88,1.12),sz=src.userData.size,w=sz.x*sc,d=sz.z*sc,off=R.w/2+d*.55+rnd(2.2,4.2),x=p[0]+nx*side*off,z=p[1]+nz*side*off;if(Math.hypot(x,z-8)<21||Math.abs(x)>88||Math.abs(z)>88||waterBlock(x,z))continue;let fx=-nx*side,fz=-nz*side,rot=Math.atan2(fx,fz),sl=slopeFoot(x,z,w,d,rot),rad=Math.hypot(w,d)*.45;if(sl.hi-sl.lo>1.35||lots.some(l=>Math.hypot(x-l.x,z-l.z)<rad+l.rad+1.5))continue;lots.push({k,x,z,rot,sc,w,d,rad});flatten.push({x,z,r:rot,w:w+1.3,d:d+1.3,y:sl.avg,m:3});colliders.push({x,z,r:rad*.72})}}}
}
function roadTexture(){const c=document.createElement('canvas');c.width=c.height=1024,ctx=c.getContext('2d');ctx.fillStyle='#667b53';ctx.fillRect(0,0,1024,1024);for(let i=0;i<5000;i++){ctx.fillStyle=i%3?'#5f754e':'#73865b';ctx.globalAlpha=.08;let x=rnd(0,1024),y=rnd(0,1024),s=rnd(.5,2.2);ctx.fillRect(x,y,s,s)}ctx.globalAlpha=1;let map=(x,z)=>[(x+WORLD)/WORLD/2*1024,(z+WORLD)/WORLD/2*1024];for(const r of roads){ctx.beginPath();let p=map(...r.p[0]);ctx.moveTo(...p);for(let i=1;i<r.p.length;i++){p=map(...r.p[i]);ctx.lineTo(...p)}ctx.strokeStyle='#8b704e';ctx.lineWidth=r.w/WORLD*512*1.35;ctx.lineCap='round';ctx.lineJoin='round';ctx.stroke();ctx.strokeStyle='#a0865e';ctx.lineWidth=r.w/WORLD*512*.82;ctx.stroke()}let t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());return t}
function terrainBuild(){const segments=MOBILE_PROFILE?112:150;let g=new THREE.PlaneGeometry(WORLD*2,WORLD*2,segments,segments);g.rotateX(-Math.PI/2);let p=g.attributes.position;for(let i=0;i<p.count;i++)p.setY(i,height(p.getX(i),p.getZ(i)));g.computeVertexNormals();let m=new THREE.MeshStandardMaterial({map:roadTexture(),roughness:.96});terrain=new THREE.Mesh(g,m);terrain.receiveShadow=true;scene.add(terrain)}
function clone(k){let a=assets[k];return a?a.clone(true):null}function box(w,h,d,mat){let m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.castShadow=m.receiveShadow=true;return m}
const foundationMat=new THREE.MeshStandardMaterial({color:0x7d756b,roughness:1});
function buildingPlace(l){let o=clone(l.k);if(!o)return;let c=Math.cos(l.rot),s=Math.sin(l.rot),hs=[];for(const [lx,lz] of [[-l.w/2,-l.d/2],[l.w/2,-l.d/2],[-l.w/2,l.d/2],[l.w/2,l.d/2],[0,0]])hs.push(height(l.x+lx*c+lz*s,l.z-lx*s+lz*c));let lo=Math.min(...hs)-.28,top=Math.max(...hs)+.05,h=top-lo,base=box(l.w*1.05,h,l.d*1.05,foundationMat);base.position.set(l.x,lo+h/2,l.z);base.rotation.y=l.rot;scene.add(base);o.scale.multiplyScalar(l.sc);o.rotation.y=l.rot;o.position.set(l.x,top-.05,l.z);l.top=top+(l.modelH||7);if(l.service){base.material=base.material.clone();o.traverse(q=>{if(!q.isMesh||!q.material)return;const mats=(Array.isArray(q.material)?q.material:[q.material]).map(m=>{const copy=m.clone();if(copy.color)copy.userData.emberBaseColor=copy.color.clone();return copy});q.material=Array.isArray(q.material)?mats:mats[0]});serviceMeshes.set(l.id,{lot:l,object:o,base,baseScale:o.scale.clone(),baseY:o.position.y,level:null,upgradeQueued:false,upgradeStart:0,upgradeRing:null})}if(l.landmark)landmarkMeshes.set(l.landmarkId,{lot:l,object:o,base});scene.add(o)}
function propPlace(k,x,z,sc=1,r=0){let o=clone(k);if(!o)return;let sz=assets[k].userData.size,w=sz.x*sc,d=sz.z*sc,c=Math.cos(r),s=Math.sin(r),hs=[];for(const [lx,lz] of [[0,0],[-w/2,-d/2],[w/2,-d/2],[-w/2,d/2],[w/2,d/2]])hs.push(height(x+lx*c+lz*s,z-lx*s+lz*c));o.scale.multiplyScalar(sc);o.rotation.y=r;o.position.set(x,Math.min(...hs)-.02,z);scene.add(o)}
function decorateServiceLevel(entry,level){const l=entry.lot,fx=Math.sin(l.rot),fz=Math.cos(l.rot),nx=-fz,nz=fx,front=l.rad*.72+1.4;if(level===1)propPlace('lamp',l.x+fx*front+nx*2,l.z+fz*front+nz*2,.9,l.rot);if(level===2)propPlace('bench',l.x+fx*front-nx*2.4,l.z+fz*front-nz*2.4,1,l.rot+Math.PI/2);if(level===3)propPlace(l.id==='market'?'stallG':'cart',l.x-fx*(l.rad*.5),l.z-fz*(l.rad*.5),.9,l.rot)}
function beginBuildingUpgrade(entry){if(entry.upgradeRing){scene.remove(entry.upgradeRing);entry.upgradeRing.geometry.dispose();entry.upgradeRing.material.dispose()}entry.upgradeQueued=false;entry.upgradeStart=performance.now();entry.object.scale.copy(entry.baseScale).multiplyScalar(.86);const l=entry.lot,ring=new THREE.Mesh(new THREE.RingGeometry(l.rad*.55,l.rad*.68,32),new THREE.MeshBasicMaterial({color:0xffd478,transparent:true,opacity:.9,side:THREE.DoubleSide,depthWrite:false}));ring.rotation.x=-Math.PI/2;ring.position.set(l.x,l.top-(l.modelH||7)+.12,l.z);ring.scale.setScalar(.45);scene.add(ring);entry.upgradeRing=ring;EmberDebug.log('WORLD','building restoration animation',l.id,entry.level)}
function updateBuildingUpgrades(time){for(const entry of serviceMeshes.values()){if(!entry.upgradeStart)continue;const progress=Math.min(1,(time-entry.upgradeStart)/1350),ease=1-(1-progress)**3,pulse=Math.sin(progress*Math.PI);entry.object.scale.copy(entry.baseScale).multiplyScalar(.86+ease*.14+pulse*.055);entry.object.position.y=entry.baseY+pulse*.75;if(entry.upgradeRing){entry.upgradeRing.scale.setScalar(.45+ease*1.3);entry.upgradeRing.material.opacity=(1-progress)*.9}if(progress>=1){entry.object.scale.copy(entry.baseScale);entry.object.position.y=entry.baseY;entry.upgradeStart=0;if(entry.upgradeRing){scene.remove(entry.upgradeRing);entry.upgradeRing.geometry.dispose();entry.upgradeRing.material.dispose();entry.upgradeRing=null}}}}
function syncTownServices(action=''){if(!serviceMeshes.size)return;for(const [id,entry] of serviceMeshes){const level=id==='mine'?1:Math.max(0,Math.min(3,Number(gameState.town?.[id])||0)),factor=[.43,.82,1,1.12][level],previous=entry.level;entry.object.traverse(q=>{if(!q.isMesh||!q.material)return;for(const mat of Array.isArray(q.material)?q.material:[q.material]){const base=mat.userData.emberBaseColor;if(base&&mat.color)mat.color.copy(base).multiplyScalar(factor)}});entry.base.material.color.setHex(level?0x7d756b:0x4e4c49);const button=serviceButtons.get(id),found=Boolean(gameState.journey?.services?.[id]);if(button)button.innerHTML=`${found?'✓ ':''}${entry.lot.name}<small>${id==='mine'?'Starter iron seam':level?`Restoration Lv ${level}`:'Needs restoration'} · tap to visit</small>`;if(propsDone){let decorated=serviceDecorationLevels.get(id)||0;while(decorated<level)decorateServiceLevel(entry,++decorated);serviceDecorationLevels.set(id,decorated)}entry.level=level;if(previous!==null&&level>previous&&action===`restore ${id}`)entry.upgradeQueued=true}}
function buildServiceButtons(){worldServices.replaceChildren();serviceButtons.clear();for(const lot of serviceLots){const button=document.createElement('button');button.className='worldService';button.type='button';button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();setServiceTarget(lot)});worldServices.append(button);serviceButtons.set(lot.id,button)}syncTownServices()}
function landmarkStatus(landmark){if(landmark.kind==='town')return landmark.subtitle;const wins=Number(gameState.explore?.regionWins?.[landmark.area])||0,claimed=Boolean(gameState.explore?.claimed?.[landmark.area]);if(landmark.id==='cave')return claimed?'Deepsteel open · fast travel unlocked':'Explorable maze · guardian within';return claimed?'Secured · fast travel unlocked':wins>=3?'Guardian revealed · tap to challenge':`${wins}/3 patrols cleared`}
function buildLandmarkButtons(){landmarkButtons.clear();for(const landmark of WORLD_LANDMARKS){if(landmark.id==='town')continue;const button=document.createElement('button'),stateLabel=landmarkStatus(landmark);button.className='worldService worldLandmark';button.type='button';button.dataset.state=stateLabel;button.innerHTML=`${landmark.icon} ${landmark.name}<small>${stateLabel}</small>`;button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();if(isLandmarkKnown(gameState,landmark))setLandmarkTarget(landmark)});worldServices.append(button);landmarkButtons.set(landmark.id,button)}}
const servicePoint=new THREE.Vector3(),serviceForward=new THREE.Vector3(),serviceDelta=new THREE.Vector3();
function updateWorldButtons(){if(caveMode()){for(const button of [...serviceButtons.values(),...landmarkButtons.values()])button.classList.remove('show');return}camera.getWorldDirection(serviceForward);for(const lot of serviceLots){const button=serviceButtons.get(lot.id);if(!button)continue;serviceDelta.set(lot.x-player.x,(lot.top||height(lot.x,lot.z)+6)-player.y,lot.z-player.z);const visible=serviceDelta.dot(serviceForward)>0&&serviceDelta.length()<115;if(!visible){button.classList.remove('show');continue}servicePoint.set(lot.x,lot.top||height(lot.x,lot.z)+6,lot.z).project(camera);if(servicePoint.z<-1||servicePoint.z>1||Math.abs(servicePoint.x)>1.08||Math.abs(servicePoint.y)>1.08){button.classList.remove('show');continue}button.style.left=`${(servicePoint.x*.5+.5)*innerWidth}px`;button.style.top=`${(-servicePoint.y*.5+.5)*innerHeight}px`;button.classList.add('show')}const known=new Set(getKnownLandmarks(gameState).map(entry=>entry.id));for(const landmark of WORLD_LANDMARKS){if(landmark.id==='town')continue;const button=landmarkButtons.get(landmark.id),lot=landmarkMeshes.get(landmark.id)?.lot;if(!button||!lot||!known.has(landmark.id)){button?.classList.remove('show');continue}const stateLabel=landmarkStatus(landmark);if(button.dataset.state!==stateLabel){button.dataset.state=stateLabel;button.innerHTML=`${landmark.icon} ${landmark.name}<small>${stateLabel}</small>`}serviceDelta.set(landmark.x-player.x,(lot.top||height(landmark.x,landmark.z)+7)-player.y,landmark.z-player.z);const visible=serviceDelta.dot(serviceForward)>0&&serviceDelta.length()<210;if(!visible){button.classList.remove('show');continue}servicePoint.set(landmark.x,lot.top||height(landmark.x,landmark.z)+7,landmark.z).project(camera);if(servicePoint.z<-1||servicePoint.z>1||Math.abs(servicePoint.x)>1.08||Math.abs(servicePoint.y)>1.08){button.classList.remove('show');continue}button.style.left=`${(servicePoint.x*.5+.5)*innerWidth}px`;button.style.top=`${(-servicePoint.y*.5+.5)*innerHeight}px`;button.classList.add('show')}}
function townPlace(){lots.forEach(buildingPlace);buildServiceButtons();buildLandmarkButtons();targetRing=new THREE.Mesh(new THREE.RingGeometry(.65,.92,32),new THREE.MeshBasicMaterial({color:0xefca80,transparent:true,opacity:.8,side:THREE.DoubleSide,depthWrite:false}));targetRing.rotation.x=-Math.PI/2;targetRing.visible=false;scene.add(targetRing)}
let propsDone=false;function decorateProps(){if(propsDone||!terrain)return;propsDone=true;rnd0=rngMaker(SEED+99);propPlace('fountain',0,8,1.15);for(let i=0;i<80;i++){let x=(i%2?-1:1)*rnd(55,155),z=rnd(-115,120);if(roadDist(x,z)<5||waterBlock(x,z))continue;propPlace(i%5===0?'tree3':i%2?'tree':'tree2',x,z,rnd(.7,1.15),rnd(0,6.28))}for(let i=0;i<roadSamples.length;i+=22){let p=roadSamples[i];if(Math.abs(p.x)>90||Math.abs(p.z)>100)continue;propPlace('lamp',p.x+p.nx*(p.w/2+1.5),p.z+p.nz*(p.w/2+1.5),.85)}for(let p of [[-9,15],[9,14],[-8,1],[8,0]])propPlace(rnd0()>.5?'stallR':'stallG',p[0],p[1],1,rnd(-.2,.2));for(let p of [[-13,8],[13,8],[0,-5]])propPlace('bench',p[0],p[1],1,rnd(0,3.14));for(let i=0;i<10;i++)propPlace('fence',-48+i*3,103,.95,Math.PI/2);for(const landmark of WORLD_LANDMARKS){if(landmark.id==='town')continue;propPlace('lamp',landmark.entry.x,landmark.entry.z,.9,0);const count=landmark.id==='forest'?22:landmark.kind==='town'?7:10;for(let i=0;i<count;i++){let a=rnd(0,Math.PI*2),radius=rnd(15,landmark.radius*.78),x=landmark.x+Math.cos(a)*radius,z=landmark.z+Math.sin(a)*radius;if(roadDist(x,z)<4||lots.some(l=>Math.hypot(x-l.x,z-l.z)<l.rad+2))continue;propPlace(landmark.id==='cave'?'rock':i%4===0?'tree3':'tree2',x,z,rnd(.72,1.12),rnd(0,Math.PI*2))}}syncTownServices()}
function grassBuild(){const grassCount=MOBILE_PROFILE?500:750;let g=new THREE.PlaneGeometry(.22,1,1,3);g.translate(0,.5,0);let m=new THREE.MeshStandardMaterial({color:0x547644,side:THREE.DoubleSide,roughness:1,transparent:true,alphaTest:.1});m.onBeforeCompile=s=>{s.uniforms.time={value:0};grassShader=s;s.vertexShader=s.vertexShader.replace('#include <common>','#include <common>\nuniform float time;').replace('#include <begin_vertex>','#include <begin_vertex>\ntransformed.x+=sin(time*2.+position.y*3.)*.09*position.y;')};let I=new THREE.InstancedMesh(g,m,grassCount),d=new THREE.Object3D(),n=0,tries=0;rnd0=rngMaker(SEED+301);while(n<grassCount&&tries++<7000){let x=rnd(-150,150),z=rnd(-125,135);if(roadDist(x,z)<4||lots.some(l=>Math.hypot(x-l.x,z-l.z)<l.rad+2))continue;d.position.set(x,height(x,z)+.03,z);d.rotation.y=rnd(0,Math.PI);let q=rnd(.6,1.3);d.scale.set(q,q,q);d.updateMatrix();I.setMatrixAt(n++,d.matrix)}I.count=n;scene.add(I)}
function drawPlan(){const known=getKnownLandmarks(gameState),visibleRoads=roads.filter(route=>route.k!=='world'||known.some(landmark=>{const end=route.p.at(-1);return Math.hypot(end[0]-landmark.entry.x,end[1]-landmark.entry.z)<48}));drawAdventureMap({context:planCanvas.getContext('2d'),size:600,worldLimit:WORLD_LIMIT,player,roads:visibleRoads,landmarks:known,height,state:gameState})}
function renderFastTravelButtons(){const unlocked=new Set(getFastTravelLandmarks(gameState).map(landmark=>landmark.id)),choices=getKnownLandmarks(gameState);mapDestinations.replaceChildren();for(const landmark of choices){const button=document.createElement('button'),available=unlocked.has(landmark.id);button.type='button';button.innerHTML=`${landmark.icon} ${landmark.name}<small>${available?'Instant travel':'Route on foot'}</small>`;button.addEventListener('click',()=>available?fastTravelTo(landmark.id):(plan.classList.remove('show'),setLandmarkTarget(landmark)));mapDestinations.append(button)}}
function fastTravelTo(landmarkId){if(gameState.explore?.combat){gameUI.notify('Finish the battle first.','bad');return false}const landmark=getFastTravelLandmarks(gameState).find(entry=>entry.id===landmarkId);if(!landmark){gameUI.notify('Secure that region before fast travelling.','bad');return false}stop(true);player.x=landmark.entry.x;player.z=landmark.entry.z;player.y=height(player.x,player.z)+1.72;yaw=Math.atan2(landmark.x-player.x,-(landmark.z-player.z));gameState.explore.encounterDist=0;writeHostedWorldPosition(gameState.explore,player,getAreaAtPosition(player));distanceSinceSave=0;positionDirty=false;commitGameState(`fast travel to ${landmark.id}`);drawPlan();renderFastTravelButtons();plan.classList.remove('show');gameUI.notify(`${landmark.icon} Fast travelled to ${landmark.name}`,'gold');EmberDebug.log('WORLD','fast travel',landmark.id);return true}
function mapWalkTarget(event){const bounds=planCanvas.getBoundingClientRect(),x=(event.clientX-bounds.left)/bounds.width*WORLD_LIMIT*2-WORLD_LIMIT,z=(event.clientY-bounds.top)/bounds.height*WORLD_LIMIT*2-WORLD_LIMIT,landmark=[...getKnownLandmarks(gameState)].sort((a,b)=>Math.hypot(x-a.x,z-a.z)-Math.hypot(x-b.x,z-b.z))[0];if(landmark&&Math.hypot(x-landmark.x,z-landmark.z)<38){plan.classList.remove('show');setLandmarkTarget(landmark)}}
planCanvas.addEventListener('click',mapWalkTarget);
window.EmberfallWorld={landmarks:WORLD_LANDMARKS,fastTravel:fastTravelTo,setStyle:applyStyle,getStyle:()=>style,getPosition:()=>({x:player.x,z:player.z,area:gameState.explore.area})};
function startLowerWays(returnWorldPos=null,{resume=false}={}){const entered=resume?getCaveRunView(gameState):enterLowerWays(gameState,returnWorldPos);const run=entered.run,layout=entered.layout,position=run.position||[caveWorld.entrance.x,caveWorld.entrance.z];stop(false);plan.classList.remove('show');player.x=position[0];player.z=position[1];player.y=caveWorld.floorY+1.72;yaw=resume?yaw:Math.PI;pitch=-.04;updateCavePosition(gameState,player);if(!resume)commitGameState('enter the Lower Ways maze');caveWorld.setVisible(true,gameState.explore.caveRun);refreshAtmosphere();$('planBtn').textContent='Return to entrance';status.textContent='Lower Ways · maze expedition';gameUI.renderJourney();updateMiniMap(performance.now(),true);if(!resume){caveBrief?.classList.add('show');setTimeout(()=>caveBrief?.classList.remove('show'),4600)}gameUI.notify(resume?'◆ Lower Ways expedition resumed':`◆ Entered the Lower Ways · ${gameState.explore.hp}/${gameState.explore.maxHp} HP`,'gold');EmberDebug.log('CAVE',resume?'resumed':'entered',{seed:layout.seed,cells:layout.cells.length,goalDistance:layout.longestPath,heals:layout.furnishings.heals.length})}
function exitCave(){const result=leaveLowerWays(gameState);if(!result.ok)return false;stop(false);caveWorld.setVisible(false,gameState.explore.caveRun);const cave= WORLD_LANDMARKS.find(entry=>entry.id==='cave'),position=result.returnWorldPos||[cave.entry.x,cave.entry.z];player.x=position[0];player.z=position[1];player.y=height(player.x,player.z)+1.72;writeHostedWorldPosition(gameState.explore,player,getAreaAtPosition(player));gameState.explore.encounterDist=0;commitGameState('leave the Lower Ways maze');refreshAtmosphere();$('planBtn').textContent='Open world map';status.textContent='World ready · expedition saved';drawPlan();gameUI.renderJourney();updateMiniMap(performance.now(),true);gameUI.notify('Returned to the Lower Ways entrance.','gold');EmberDebug.log('CAVE','left expedition');return true}
function routeCaveEntrance(){if(!caveMode())return false;const distance=Math.hypot(player.x-caveWorld.entrance.x,player.z-caveWorld.entrance.z);if(distance<2.2)return exitCave();beginNavigation({x:caveWorld.entrance.x,z:caveWorld.entrance.z});pendingCaveAction='exit';gameUI.notify('Route marked back to the cave entrance.','gold');return true}
function routeCaveDeeper(){if(!caveMode())return false;const view=getCaveRunView(gameState),known=new Set(view.run.discovered),goalKnown=known.has(view.layout.goal);let target=goalKnown?view.layout.cells[view.layout.goal]:view.layout.cells.filter(cell=>!known.has(cell.index)&&cell.distance>=0&&cell.passages).filter(cell=>{for(const direction of [1,2,4,8])if(cell.passages&direction){const neighbour=direction===1?cell.index-view.layout.width:direction===2?cell.index+1:direction===4?cell.index+view.layout.width:cell.index-1;if(known.has(neighbour))return true}return false}).sort((a,b)=>b.distance-a.distance)[0];if(!target)target=view.layout.cells[view.layout.goal];const position=caveWorld.cellToWorld(target.index);beginNavigation({x:position.x,z:position.z});pendingCaveAction='frontier';gameUI.notify(goalKnown?'Guardian route marked.':'Route marked to the deepest known passage.','gold');EmberDebug.log('CAVE','route hint',{target:target.index,goalKnown});return true}
function blocked(x,z){if(caveMode()){const limitX=(caveWorld.layout.width-1)*CAVE_CELL_SIZE/2+CAVE_CELL_SIZE*.48,limitZ=(caveWorld.layout.height-1)*CAVE_CELL_SIZE/2+CAVE_CELL_SIZE*.48;return Math.abs(x)>limitX||Math.abs(z)>limitZ}if(Math.abs(x)>WORLD_LIMIT||Math.abs(z)>WORLD_LIMIT||waterBlock(x,z))return true;return colliders.some(c=>Math.hypot(x-c.x,z-c.z)<c.r+.55)}
function navFind(end,step=7){
 if(caveMode())return caveWorld.findPath(player,end);
 const margin=28,minX=Math.max(-WORLD_LIMIT,Math.floor((Math.min(player.x,end.x)-margin)/step)*step),maxX=Math.min(WORLD_LIMIT,Math.ceil((Math.max(player.x,end.x)+margin)/step)*step),minZ=Math.max(-WORLD_LIMIT,Math.floor((Math.min(player.z,end.z)-margin)/step)*step),maxZ=Math.min(WORLD_LIMIT,Math.ceil((Math.max(player.z,end.z)+margin)/step)*step),NX=Math.round((maxX-minX)/step)+1,NZ=Math.round((maxZ-minZ)/step)+1;
 const G=p=>[clamp(Math.round((p.x-minX)/step),0,NX-1),clamp(Math.round((p.z-minZ)/step),0,NZ-1)],W=(x,z)=>({x:minX+x*step,z:minZ+z*step}),[sx,sz]=G(player),[ex,ez]=G(end),open=[{x:sx,z:sz,g:0,f:0}],came=new Map(),gs=new Map([[key(sx,sz),0]]),closed=new Set(),dirs=[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]];
 let n=0;while(open.length&&n++<12000){let c=heapPop(open),K=key(c.x,c.z);if(closed.has(K))continue;closed.add(K);if(c.x===ex&&c.z===ez){let P=[];while(c){P.push(W(c.x,c.z));c=came.get(key(c.x,c.z))}P.reverse();P[0]={x:player.x,z:player.z};P[P.length-1]=end;return P}for(const [dx,dz] of dirs){let nx=c.x+dx,nz=c.z+dz;if(nx<0||nz<0||nx>=NX||nz>=NZ)continue;let w=W(nx,nz);if(blocked(w.x,w.z)&&!(nx===ex&&nz===ez))continue;let cw=W(c.x,c.z),rd=Math.max(0,roadDist(w.x,w.z)),slope=Math.abs(height(w.x,w.z)-height(cw.x,cw.z)),ng=c.g+Math.hypot(dx,dz)*(1+clamp(rd/10,0,1)*.75+slope*.4),nk=key(nx,nz);if(ng<(gs.get(nk)??1e9)){gs.set(nk,ng);came.set(nk,c);heapPush(open,{x:nx,z:nz,g:ng,f:ng+Math.hypot(nx-ex,nz-ez)})}}}
 return[end]
}
function nearestService(p){return serviceLots.find(l=>Math.hypot(p.x-l.x,p.z-l.z)<l.rad+5)||null}
function beginNavigation(end,service=null,landmark=null){pendingCaveAction=null;pendingService=service;pendingLandmark=landmark;const rawPath=navFind(end);nav=caveMode()?rawPath:smoothNavigationPath(rawPath,blocked,{sampleSpacing:1.1,maxSkip:7});if(nav.length<2)nav=[{x:player.x,z:player.z},end];navI=1;routeHeadingReturn=.3;targetRing.position.set(end.x,groundHeight(end.x,end.z)+.08,end.z);targetRing.visible=true;walk.classList.add('show');EmberDebug.log('NAV','route prepared',{rawNodes:rawPath.length,smoothNodes:nav.length})}
function setTarget(p){beginNavigation({x:p.x,z:p.z},null)}
function setServiceTarget(service){let dx=player.x-service.x,dz=player.z-service.z,d=Math.hypot(dx,dz)||1,stand=service.rad*.72+1.35;beginNavigation({x:service.x+dx/d*stand,z:service.z+dz/d*stand},service);EmberDebug.log('WORLD','walking to service',service.id)}
function setLandmarkTarget(landmark){plan.classList.remove('show');beginNavigation({x:landmark.entry.x,z:landmark.entry.z},null,landmark);EmberDebug.log('WORLD','walking to landmark',landmark.id)}
function journeyWorldAction(goal){if(goal?.worldAction==='cave-goal'&&caveMode())return routeCaveDeeper();if(goal?.serviceId){const service=serviceLots.find(entry=>entry.id===goal.serviceId);if(!service)return false;plan.classList.remove('show');setServiceTarget(service);return true}const landmark=WORLD_LANDMARKS.find(entry=>entry.id===goal?.landmarkId);if(!landmark||!isLandmarkKnown(gameState,landmark))return false;plan.classList.remove('show');if(goal.worldAction==='patrol'&&landmark.kind==='region'){const points=[ [20,-20],[-18,-24],[-25,17],[18,23] ],wins=Number(gameState.explore?.regionWins?.[landmark.area])||0,travelPhase=Math.floor((Number(gameState.explore?.encounterDist)||0)/3),index=(wins+(gameState.explore?.encounters||0)+travelPhase)%points.length,[ox,oz]=points[index];beginNavigation({x:landmark.x+ox,z:landmark.z+oz},null,landmark);gameUI.notify(`Patrolling ${landmark.name} · encounters build with distance`,'gold');EmberDebug.log('WORLD','journey patrol',landmark.id,index);return true}setLandmarkTarget(landmark);return true}
function stop(cancelDestination=true){nav=[];navI=0;routeHeadingReturn=0;if(cancelDestination){pendingService=null;pendingLandmark=null;pendingCaveAction=null}if(targetRing)targetRing.visible=false;walk.classList.remove('show')}
function finishNavigation(){const service=pendingService,landmark=pendingLandmark,caveAction=pendingCaveAction;pendingService=null;pendingLandmark=null;pendingCaveAction=null;stop(false);if(caveAction==='exit'){exitCave();return}if(caveAction==='frontier'){gameUI.renderJourney();gameUI.notify('New chamber reached · choose the next passage.','gold');return}if(service){const building=serviceMeshes.get(service.id),upgrading=Boolean(building?.upgradeQueued),visit=recordServiceVisit(gameState,service.id);if(visit.discovered){if(service.id==='mine')gameState.active='mining';if(service.id==='smelter')gameState.active='smelting';const unlocked={mine:'Mining',smelter:'Smelting',forge:'Forge',market:'Market'}[service.id]||service.name;commitGameState(`discover Greyfen ${service.id}`);gameUI.notify(`✓ ${unlocked} unlocked`,'gold')}EmberDebug.log('WORLD','service reached',service.id,service.tab,{discovered:visit.discovered,upgrading});if(upgrading){beginBuildingUpgrade(building);gameUI.notify(`${service.name} restored · the town is changing`,'gold')}else gameUI.open(service.tab)}else if(landmark){const areaInfo=getAreaAtPosition(player);writeHostedWorldPosition(gameState.explore,player,areaInfo);distanceSinceSave=0;positionDirty=false;if(landmark.id==='cave'){startLowerWays([player.x,player.z]);return}if(isGuardianAvailable(gameState,landmark)){const result=gameUI.startEncounter({boss:true,origin:{area:landmark.area,pos:[player.x,player.z],yaw,z:player.y}});if(result.ok)EmberDebug.log('WORLD','guardian challenged',landmark.id);return}const welcome=recordTownArrival(gameState,landmark.id);commitGameState(welcome.discovered?`complete ${landmark.id} welcome contract`:`arrive at ${landmark.id}`);gameUI.renderJourney();gameUI.notify(welcome.discovered?`${landmark.icon} ${welcome.name} · +${welcome.coins}c · +${welcome.xp} XP`:`${landmark.icon} ${landmark.name} · ${landmarkStatus(landmark)}`,'gold');EmberDebug.log('WORLD','landmark reached',landmark.id,areaInfo.area,{welcome:welcome.discovered})}}
$('stop').onclick=()=>stop(true);
function move(dt){if(gameState.explore?.combat||!nav.length)return;if(navI>=nav.length){finishNavigation();return}let t=nav[navI],dx=t.x-player.x,dz=t.z-player.z,d=Math.hypot(dx,dz);if(d<.5){navI++;routeHeadingReturn=Math.max(routeHeadingReturn,.24);if(navI>=nav.length)finishNavigation();return}dx/=d;dz/=d;let nx=player.x+dx*9.7*dt,nz=player.z+dz*9.7*dt,travelled=0;if(!blocked(nx,nz)){travelled=Math.hypot(nx-player.x,nz-player.z);player.x=nx;player.z=nz}else{navI++;routeHeadingReturn=Math.max(routeHeadingReturn,.24);if(navI>=nav.length)finishNavigation()}player.y=groundHeight(player.x,player.z)+1.72;if(!travelled)return;const areaInfo=currentAreaInfo();let caveStep=null;if(caveMode()){caveStep=updateCavePosition(gameState,player);if(caveStep.discovered){gameUI.renderJourney();EmberDebug.log('CAVE','chamber discovered',caveStep.cell.index,`${caveStep.run.discovered.length}/${caveStep.layout.cells.length}`)}const healing=useNearbyCaveHealing(gameState,player);if(healing.healed){caveWorld.setRun(gameState.explore.caveRun);distanceSinceSave=0;positionDirty=false;commitGameState('drink from an Embermoss spring');gameUI.notify(`✚ Embermoss restored ${healing.amount} HP · ${healing.hp}/${healing.maxHp}`,'gold');EmberDebug.log('CAVE','healing spring used',healing.cell,healing.amount)}if(caveStep.atGoal&&!gameState.explore.claimed.cave){const guardian=markCaveBossStarted(gameState);if(guardian.ok){stop(false);const result=gameUI.startEncounter({boss:true,enemyId:'custodian',origin:{area:'cave',pos:[player.x,player.z],yaw,z:player.y}});if(result.ok){EmberDebug.log('CAVE','guardian chamber reached',caveStep.cell.index);return}}}}else writeHostedWorldPosition(gameState.explore,player,areaInfo);distanceSinceSave+=travelled;positionDirty=true;const regionGuardian=areaInfo.landmark?.kind==='region'&&isGuardianAvailable(gameState,areaInfo.landmark),securedCave=areaInfo.area==='cave'&&gameState.explore.claimed.cave,encounter=registerTravelDistance(gameState,travelled/9,{suppressed:regionGuardian||securedCave||Boolean(caveStep?.atGoal),origin:{area:areaInfo.area,pos:[player.x,player.z],yaw,z:player.y}});if(encounter.started){stop(false);distanceSinceSave=0;positionDirty=false;commitGameState(caveMode()?'start Lower Ways encounter':'start 3D travel combat');gameUI.render();EmberDebug.log('WORLD','distance encounter started',areaInfo.area,encounter.enemy?.id);return}if(distanceSinceSave>=WORLD_POSITION_SAVE_INTERVAL){distanceSinceSave=0;positionDirty=false;commitGameState(caveMode()?'checkpoint Lower Ways position':'checkpoint 3D world position')}}
function showMineUnlock(pending){if(!unlockOverlay)return false;$('unlockIcon').textContent=pending.icon||'◆';$('unlockEyebrow').textContent=pending.eyebrow||'MINE UNLOCKED';$('unlockTitle').textContent=pending.title;$('unlockText').textContent=pending.text;$('unlockCoins').textContent=`+${pending.rewards?.coins||0} coin`;$('unlockXp').textContent=`+${pending.rewards?.xp||0} XP`;unlockOverlay.classList.add('show');unlockOverlay.setAttribute('aria-hidden','false');caveWorld?.setRun(gameState.explore.caveRun);return true}
function dismissMineUnlock(returnToEntrance=false){unlockOverlay?.classList.remove('show');unlockOverlay?.setAttribute('aria-hidden','true');const pending=gameState.explore?.pending;if(pending){gameState.explore.pending=null;completeLowerWays(gameState);commitGameState('acknowledge Deepsteel unlock')}gameUI.renderJourney();if(returnToEntrance&&caveMode())routeCaveEntrance();else gameUI.notify('◆ Deepsteel is now visible in Work and Forge.','gold')}
$('unlockReturn').onclick=()=>dismissMineUnlock(true);$('unlockStay').onclick=()=>dismissMineUnlock(false);
function acknowledgePendingResult(){const pending=gameState.explore?.pending;if(!pending)return false;if(pending.type==='mine-unlocked')return showMineUnlock(pending);gameState.explore.pending=null;commitGameState(`acknowledge ${pending.type||'region'} result`);gameUI.notify(`${pending.icon||'◆'} ${pending.title}`,'gold');return true}
function syncAfterCombat(){const active=Boolean(gameState.explore?.combat);if(wasCombatActive&&!active){resetCaveBossAfterCombat(gameState);const physicalArea=currentAreaInfo(),returnedToGreyfen=gameState.explore.area==='town'&&gameState.explore.townId==='town'&&(player.y<-20||physicalArea.landmark?.id!=='town');if(returnedToGreyfen){stop(true);caveWorld?.setVisible(false,gameState.explore.caveRun);const greyfen=WORLD_LANDMARKS[0];player.x=greyfen.entry.x;player.z=greyfen.entry.z;player.y=height(player.x,player.z)+1.72;writeHostedWorldPosition(gameState.explore,player,getAreaAtPosition(player));commitGameState('return to Greyfen after defeat');refreshAtmosphere();$('planBtn').textContent='Open world map';gameUI.renderJourney();gameUI.notify('You were forced back to Greyfen.','bad')}else{if(caveMode())updateCavePosition(gameState,player);else writeHostedWorldPosition(gameState.explore,player,physicalArea);acknowledgePendingResult();if(!gameState.explore.pending&&caveMode()&&pendingCaveAction==='frontier'){routeCaveDeeper();gameUI.notify('Encounter cleared · deeper route resumed.','gold')}else if(!gameState.explore.pending&&caveMode()&&pendingCaveAction==='exit'){routeCaveEntrance();gameUI.notify('Encounter cleared · return route resumed.','gold')}else if(pendingLandmark&&!caveMode()){const destination=pendingLandmark;setLandmarkTarget(destination);gameUI.notify(`Journey resumed to ${destination.name}.`,'gold')}}drawPlan()}wasCombatActive=active}
let lightAnchorX=Infinity,lightAnchorZ=Infinity;function cameraUpdate(){let cy=Math.cos(pitch),v=new THREE.Vector3(Math.sin(yaw)*cy,Math.sin(pitch),-Math.cos(yaw)*cy);camera.position.set(player.x,player.y,player.z);camera.lookAt(player.x+v.x*10,player.y+v.y*10,player.z+v.z*10);if(Math.hypot(player.x-lightAnchorX,player.z-lightAnchorZ)>10){lightAnchorX=player.x;lightAnchorZ=player.z;sun.position.set(player.x-120,player.y+160,player.z+95);sun.target.position.set(player.x,groundHeight(player.x,player.z),player.z);sun.target.updateMatrixWorld()}}
function updateRouteHeading(dt){if(routeHeadingReturn<=0||ptr||!nav.length||navI>=nav.length)return;const lookAt=routeLookAhead(player,nav,navI,caveMode()?7:12),heading=lookAt&&routeHeading(player,lookAt);if(heading==null){routeHeadingReturn=0;return}routeHeadingReturn-=dt;if(routeHeadingReturn<=0)yaw=heading;else yaw=dampAngle(yaw,heading,13,dt)}
function rayGround(x,y){let r=canvas.getBoundingClientRect();mouse.x=(x-r.left)/r.width*2-1;mouse.y=-((y-r.top)/r.height*2-1);ray.setFromCamera(mouse,camera);return caveMode()?ray.intersectObjects(caveWorld.floorTargets,false)[0]?.point:ray.intersectObject(terrain,false)[0]?.point}
let ptr=null;canvas.onpointerdown=e=>{canvas.setPointerCapture?.(e.pointerId);routeHeadingReturn=0;ptr={id:e.pointerId,x:e.clientX,y:e.clientY,m:0}};canvas.onpointermove=e=>{if(!ptr||ptr.id!==e.pointerId)return;let dx=e.clientX-ptr.x,dy=e.clientY-ptr.y;ptr.x=e.clientX;ptr.y=e.clientY;ptr.m+=Math.hypot(dx,dy);yaw+=dx*.0045;pitch=clamp(pitch-dy*.0037,-.62,.58)};function end(e){if(!ptr||ptr.id!==e.pointerId)return;const looked=ptr.m>=9;if(!looked){let p=rayGround(e.clientX,e.clientY),service=p&&nearestService(p);if(service||p&&!blocked(p.x,p.z)){service?setServiceTarget(service):setTarget(p);tap.style.left=e.clientX+'px';tap.style.top=e.clientY+'px';tap.style.display='block';setTimeout(()=>tap.style.display='none',300)}}ptr=null;if(looked&&nav.length)routeHeadingReturn=.38}canvas.onpointerup=end;canvas.onpointercancel=end;
function setMiniMapCollapsed(collapsed){miniMapPanel?.classList.toggle('collapsed',collapsed);if(miniMapToggle){miniMapToggle.textContent=collapsed?'▣':'−';miniMapToggle.setAttribute('aria-expanded',String(!collapsed));miniMapToggle.setAttribute('aria-label',collapsed?'Expand local map':'Minimise local map')}try{localStorage.setItem('emberfall_minimap_collapsed',collapsed?'1':'0')}catch{}if(!collapsed)updateMiniMap(performance.now(),true)}
let initialMiniMapCollapsed=false;try{initialMiniMapCollapsed=localStorage.getItem('emberfall_minimap_collapsed')==='1'}catch{}setMiniMapCollapsed(initialMiniMapCollapsed);if(miniMapToggle)miniMapToggle.onclick=()=>setMiniMapCollapsed(!miniMapPanel.classList.contains('collapsed'));
$('planBtn').onclick=()=>{if(caveMode()){routeCaveEntrance();return}drawPlan();renderFastTravelButtons();plan.classList.toggle('show')};
addEventListener('pagehide',()=>{if(positionDirty){if(caveMode())updateCavePosition(gameState,player);else writeHostedWorldPosition(gameState.explore,player,getAreaAtPosition(player));commitGameState(caveMode()?'save Lower Ways position on exit':'save 3D world position on exit')}});
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
function updatePlayerHealth(){const maxHp=Math.max(1,Number(gameState.explore?.maxHp)||1),hp=clamp(Number(gameState.explore?.hp)||0,0,maxHp),ratio=hp/maxHp;if(playerHealthText)playerHealthText.textContent=`${Math.ceil(hp)} / ${Math.ceil(maxHp)} HP`;if(playerHealthFill)playerHealthFill.style.width=`${ratio*100}%`;if(playerVitals)playerVitals.dataset.critical=ratio<=.3?'true':'false'}
function updateMiniMap(t,force=false){updatePlayerHealth();if(!miniCanvas||!force&&t-lastMiniMap<180)return;lastMiniMap=t;if(caveMode()){const view=getCaveRunView(gameState);drawCaveMiniMap({context:miniCanvas.getContext('2d'),size:220,layout:view.layout,run:view.run,player,yaw,route:nav.slice(Math.max(0,navI-1))});if(miniArea)miniArea.textContent='The Lower Ways';if(miniSafety){miniSafety.textContent='DANGER';miniSafety.dataset.safe='false'}caveHealth?.classList.remove('show');return}caveHealth?.classList.remove('show');const areaInfo=getAreaAtPosition(player),known=getKnownLandmarks(gameState);drawLiveMiniMap({context:miniCanvas.getContext('2d'),size:220,player,yaw,roads,landmarks:known,route:nav.slice(Math.max(0,navI-1)),areaInfo});if(miniArea)miniArea.textContent=areaInfo.landmark?.name||'The Wild Roads';if(miniSafety){const safe=areaInfo.area==='town';miniSafety.textContent=safe?'SAFE TOWN':'ENCOUNTERS ACTIVE';miniSafety.dataset.safe=safe?'true':'false'}}
const npcPoint=new THREE.Vector3();
function updateNpcSpeech(t){if(!npcSpeech||!townLife||t-lastNpcSpeech<140)return;lastNpcSpeech=t;if(caveMode()||gameState.explore?.combat||$('gamePanel')?.classList.contains('show')){npcSpeech.classList.remove('show');return}const nearby=townLife.nearby(player);if(!nearby){npcSpeech.classList.remove('show');return}npcPoint.copy(nearby.npc.position);npcPoint.y+=1.9;npcPoint.project(camera);if(npcPoint.z<-1||npcPoint.z>1||Math.abs(npcPoint.x)>1.1||Math.abs(npcPoint.y)>1.1){npcSpeech.classList.remove('show');return}npcName.textContent=nearby.name;npcLine.textContent=nearby.line;npcSpeech.style.left=`${clamp((npcPoint.x*.5+.5)*innerWidth,72,innerWidth-72)}px`;npcSpeech.style.top=`${clamp((-npcPoint.y*.5+.5)*innerHeight,70,innerHeight-90)}px`;npcSpeech.classList.add('show')}
function frame(t){let dt=Math.min(.04,(t-last)/1000);last=t;syncAfterCombat();move(dt);updateRouteHeading(dt);cameraUpdate();updateWorldButtons();updateMiniMap(t);townLife?.update(t*.001);caveWorld?.update(t*.001,player);updateNpcSpeech(t);updateBuildingUpgrades(t);skyLife?.update(dt);if(grassShader)grassShader.uniforms.time.value=t*.001;if(targetRing?.visible)targetRing.material.opacity=.55+.25*Math.sin(t*.006);renderer.render(scene,camera);requestAnimationFrame(frame)}
async function init(){try{sky();lighting();skyLife=createSkyLife({THREE,scene,mobile:MOBILE_PROFILE});status.textContent='Loading town…';let n=await loadBuildings();loadingText.textContent='Opening the roads…';rnd0=rngMaker(SEED);roadsGenerate();lotsGenerate();terrainBuild();caveWorld=createLowerWaysVisuals({THREE,scene,layout:initialCaveView.layout,mobile:MOBILE_PROFILE});createAdventureBackdrop({THREE,scene,height,mobile:MOBILE_PROFILE});townLife=createLivingTowns({THREE,scene,height,landmarks:WORLD_LANDMARKS,mobile:MOBILE_PROFILE});townPlace();grassBuild();drawPlan();player.y=groundHeight(player.x,player.z)+1.72;applyStyle('realistic');if(initialCaveView.run.active)startLowerWays(null,{resume:true});else updateMiniMap(performance.now(),true);status.classList.add('ready');if(!caveMode())status.textContent=`Greyfen ready · ${saveBridge.found?'save linked':'new journey'}`;loader.classList.add('hide');EmberDebug.log('PERF',MOBILE_PROFILE?'mobile profile':'desktop profile',{buildingTypes:n,pixelRatio:renderer.getPixelRatio(),terrainSegments:MOBILE_PROFILE?112:150,grass:MOBILE_PROFILE?500:750,caveDrawGroups:7});loadProps();if(!gameState.explore.combat){setTimeout(acknowledgePendingResult,500);if(!caveMode())setTimeout(()=>gameUI.maybeShowIntro(),760)}requestAnimationFrame(frame)}catch(e){fail(e)}}init();
})();
